### ISSUE TITLE
rake install doesnt work

### ISSUE THREAD

**Issue by jothirams** [zhaocai/alfred2-top-workflow#6]
Hello

I just cloned the repo today and when I run rake install or rake -T, inside the repo, I get the following error:

alfred2-top-workflow/ (master) $ rake -T
rake aborted!
cannot load such file -- plist
/User/x/alfred_workflows/alfred2-top-workflow/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by zhaocai** [comment]
`sudo gem install plist`
