### ISSUE TITLE
Activity Monitor Memory Consumption

### ISSUE THREAD

**Issue by jothirams** [zhaocai/alfred2-top-workflow#7]
Hello,

This is more a feature request:

In Activity Monitor, it shows the total memory that is used, the memory that is wired etc.

Is it possible to get that value as well in this workflow.

**Comment by zhaocai** [comment]
it should be possible. but I do not see how to organize the layout of each entry. The space for alfred window is limited.

**Comment by jothirams** [comment]
It would be good if you can do it similar to the current top -m option that shows the CPU, memory etc in subtext if we can type

Memory

And it shows all these values in the subtext.

**Comment by zhaocai** [comment]
Thanks for the suggestion. But for now, I cannot convince myself the necessity of showing detailed memory usage. This workflow is supposed to be fast, I do not want to make it bloated.

**Comment by jothirams** [comment]
Okay. The idea behind was I wanted to see if my swap was used heavily in mavericks which will give me an idea to kill some processes.
